# GitHub Marketplace listing recommendation:
# Primary Category: Utilities
# Another Category (optional): Publishing
name: 'Blackout Secure MCP Registry Engine'
description: 'A static, host‑agnostic registry engine for MCP services, supporting validation, listing, and discovery.'
author: 'Blackout Secure'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  source:
    description: 'Path to the servers directory'
    required: false
    default: './servers'
  output:
    description: 'Path to the output base directory (registry will be generated under <output>/registry)'
    required: false
    default: './dist'
  deployment_environment:
    description: 'Deployment environment profile (github for GitHub Pages, cloudflare for Cloudflare Pages/Workers)'
    required: false
    default: 'github'
  config:
    description: 'Optional path to custom registry config file (supports version and externalRepositories)'
    required: false
  external_repositories:
    description: 'Optional JSON array of additional servers roots (e.g. ["../team/servers", {"path":"../shared/servers"}])'
    required: false
