name: 'MCP Registry Generator'
description: 'Generate static MCP registry from server definitions'
author: 'MCP Registry Engine'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  source:
    description: 'Path to the servers directory'
    required: false
    default: './servers'
  output:
    description: 'Path to the output registry directory'
    required: false
    default: './registry'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      shell: bash
      run: npm install
      working-directory: ${{ github.action_path }}
    
    - name: Generate registry
      shell: bash
      run: |
        echo "🚀 Generating MCP Registry..."
        node ${{ github.action_path }}/scripts/generate-registry.js
        echo "✓ Registry generated successfully"
      env:
        SERVERS_DIR: ${{ inputs.source }}
        REGISTRY_DIR: ${{ inputs.output }}
