# GitHub Marketplace listing recommendation:
# Primary Category: Utilities
# Another Category (optional): Publishing
name: 'Blackout Secure MCP Registry Engine'
description: 'A static, host‑agnostic registry engine for MCP services, supporting validation, listing, and discovery.'
author: 'Blackout Secure'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  action_type:
    description: 'Action mode to run (generate_registry, validate_registry, generate_server_manifest, validate_server_manifest)'
    required: true
  log_level:
    description: 'Optional log verbosity level (suggested: debug, info, warn, error)'
    required: false
    default: 'info'
  source:
    description: 'Path to the servers directory'
    required: false
    default: './servers'
  output:
    description: 'Public output directory name under internal base output path (default: public)'
    required: false
    default: 'public'
  output_directory:
    description: 'Base output directory path for generated registry artifacts (default: dist)'
    required: false
    default: 'dist'
  deployment_environment:
    description: 'Deployment environment profile (github for GitHub Pages, cloudflare for Cloudflare Pages/Workers, none for host-agnostic static output)'
    required: false
    default: 'github'
  config:
    description: 'Optional path to custom registry config file (supports version and externalRepositories)'
    required: false
  upload_artifacts:
    description: 'Upload generated registry output as a GitHub Actions artifact (generate_registry only)'
    required: false
    default: 'false'
  artifact_name:
    description: 'Artifact name used when upload_artifacts is enabled'
    required: false
    default: 'mcp-registry-files'
  artifact_retention_days:
    description: 'Optional artifact retention in days (positive integer) when upload_artifacts is enabled'
    required: false
  server_slug:
    description: 'Server folder slug under source (required for generate_server_manifest and validate_server_manifest)'
    required: false
  server_name:
    description: 'Server manifest name (required for generate_server_manifest)'
    required: false
  server_title:
    description: 'Optional server title for generated/updated server.json'
    required: false
  server_description:
    description: 'Server manifest description (required for generate_server_manifest)'
    required: false
  server_website_url:
    description: 'Optional server websiteUrl for generated/updated server.json'
    required: false
  repository_url:
    description: 'Optional repository URL for generated/updated server.json'
    required: false
  repository_source:
    description: 'Repository source for generated/updated server.json when repository_url is set'
    required: false
    default: 'github'
  repository_subfolder:
    description: 'Optional repository subfolder for generated/updated server.json'
    required: false
  server_version:
    description: 'Version manifest filename/version field for generated/updated versions/<version>.json'
    required: false
    default: '1.0.0'
  release_date:
    description: 'Optional ISO date (YYYY-MM-DD) for generated/updated version manifest releaseDate'
    required: false
  package_registry_type:
    description: 'Package registryType for generated/updated version manifest package entry'
    required: false
    default: 'npm'
  package_identifier:
    description: 'Optional package identifier for generated/updated version manifest package entry'
    required: false
  package_transport_type:
    description: 'Package transport.type for generated/updated version manifest package entry'
    required: false
    default: 'stdio'
