name: 'Blackout Secure MCP Registry Engine'
description: 'A host-agnostic static MCP Registry Engine that indexes, validates, and publishes MCP services. Generates a complete MCP registry under /registry/v0.1 for deployment to any static hosting environment or platform.'
author: 'Blackout Secure'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  source:
    description: 'Path to the servers directory'
    required: false
    default: './servers'
  output:
    description: 'Path to the output registry directory'
    required: false
    default: './registry'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: npm ci --omit=dev
      working-directory: ${{ github.action_path }}

    - name: Generate registry
      shell: bash
      run: |
        echo "🚀 Generating MCP Registry..."
        node ${{ github.action_path }}/scripts/generate-registry.js
        echo "✓ Registry generated successfully"
      env:
        SERVERS_DIR: ${{ inputs.source }}
        REGISTRY_DIR: ${{ inputs.output }}
